#!/bin/bash

# create_script
# This script creates a new bash script, sets permissions and more
# Author: jvillete

# Is there an argument?
if [[ ! $1 ]]; then
	echo "Missing argument" >&2
	exit 1
fi

declare open_editor=""
if [[ $# -eq 1 ]]; then
	open_editor="true"
fi

declare -r bindir="${HOME}/git/bashing/pluralsight"

# Check bin directory exists
if [[ ! -d $bindir ]]; then
	# if not: create bin directory
	if mkdir "$bindir"; then
		echo "created ${bindir}"
	else
		echo "Could not create ${bindir}." >&2
		exit 1
	fi
fi

declare scriptname=""
while [[ $1 ]]; do
	scriptname="$1"
	filename="${bindir}/${scriptname}"

	if [[ -e $filename ]]; then
		echo "File ${filename} already exists" >&2
		shift
		continue
	fi
	
	if type "$scriptname" 1> /dev/null 2>&1; then
		echo "There is already a command with name ${scriptname}" >&2
		shift
		continue
	fi

	# Create a script with a single line
	echo '#!/bin/bash' >> "$filename"
	echo '' >> "$filename"
	echo 'exit 0' >> "$filename"
	
	# Add executable permission
	chmod u+x "$filename"

	# Create a symbolic link at $HOME bin (available on $PATH)
	ln -s "${filename}" "${HOME}/bin"
	
	shift
done

# Open with editor
if [[ $open_editor ]]; then
	echo opening
	if [[ $EDITOR ]]; then
		$EDITOR "$filename"
	else
		vi "$filename"
	fi
fi

exit 0
