#!/bin/bash

# Simple note-taking script
# Author: jvillete

# get the date
date=$(date)

# get topic
topic="$1"

# filename to write to
filename="${HOME}/${topic}notes.txt"

# Ask user for input
read -p "Your note: " note

if [[ $note ]]; then
	echo "$date: $note" >> "$filename"
	echo "Note '$note' saved to $filename"
else
	echo "No input; note wasn't saved." 1>&2
	exit 1
fi

exit 0
